import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, FileSpreadsheet, Printer, RefreshCw, Users, ShoppingBag, CircleDollarSign, TrendingUp, X } from 'lucide-react';
import { getDashboardOrders, OrderRecord } from '../services/ordersService';
import { formatBrazilPhone } from '../utils/phone';
import { downloadXlsx } from '../utils/xlsx';

type Period = 'today' | 'yesterday' | '7d' | '30d' | 'month' | 'prevmonth' | 'custom';
const dateKey = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money = (n: number) => Number(n || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const when = (s: string) => new Date(s).toLocaleString('pt-BR');
const escapeHtml = (value: unknown) => String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');

export default function SalesDashboard({ onBack }: { onBack: () => void }) {
  const [orders, setOrders] = useState<OrderRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [period, setPeriod] = useState<Period>('30d');
  const [startDate, setStartDate] = useState(() => dateKey(new Date(Date.now()-29*86400000)));
  const [endDate, setEndDate] = useState(() => dateKey(new Date()));
  const [selected, setSelected] = useState<OrderRecord | null>(null);
  const [selectedClientId, setSelectedClientId] = useState<string | null>(null);

  const refresh = useCallback(async (background = false) => {
    if (!background) setLoading(true); setError('');
    try { setOrders(await getDashboardOrders()); }
    catch { setError('Não foi possível carregar os pedidos. Confirme se a migração do Dashboard foi aplicada no Supabase e se sua conta tem permissão administrativa.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    void refresh();
    const update = () => { if (document.visibilityState === 'visible') void refresh(true); };
    const interval = window.setInterval(update, 15000);
    window.addEventListener('focus', update);
    document.addEventListener('visibilitychange', update);
    return () => { window.clearInterval(interval); window.removeEventListener('focus', update); document.removeEventListener('visibilitychange', update); };
  }, [refresh]);

  const range = useMemo(() => {
    const now = new Date(); let from = new Date(now); let to = new Date(now);
    if (period === 'yesterday') { from.setDate(from.getDate()-1); to.setDate(to.getDate()-1); }
    if (period === '7d') from.setDate(from.getDate()-6);
    if (period === '30d') from.setDate(from.getDate()-29);
    if (period === 'month') from = new Date(now.getFullYear(),now.getMonth(),1);
    if (period === 'prevmonth') { from = new Date(now.getFullYear(),now.getMonth()-1,1); to = new Date(now.getFullYear(),now.getMonth(),0); }
    return { from: period === 'custom' ? startDate : dateKey(from), to: period === 'custom' ? endDate : dateKey(to) };
  }, [period,startDate,endDate]);
  const filtered = useMemo(() => orders.filter(o => { const d = dateKey(new Date(o.created_at)); return d >= range.from && d <= range.to; }), [orders,range]);
  const sales = filtered;
  const total = sales.reduce((n,o)=>n+Number(o.total),0);
  const clients = new Map<string,{id:string;name:string;phone:string;orders:number;spent:number;first:string;last:string}>();
  for (const o of filtered) {
    const key = o.cliente_id; const old = clients.get(key); const time = new Date(o.created_at).getTime();
    if (!old) clients.set(key,{id:key,name:o.clientes?.nome || 'Cliente',phone:o.clientes?.telefone || '',orders:1,spent:Number(o.total),first:o.created_at,last:o.created_at});
    else { old.orders++; old.spent+=Number(o.total); if(time<new Date(old.first).getTime())old.first=o.created_at; if(time>new Date(old.last).getTime())old.last=o.created_at; }
  }
  for (const o of orders) { const c=clients.get(o.cliente_id); if(c){if(new Date(o.created_at)<new Date(c.first))c.first=o.created_at;if(new Date(o.created_at)>new Date(c.last))c.last=o.created_at;} }
  const customerHistory = selectedClientId ? orders.filter(o => o.cliente_id === selectedClientId) : [];
  const customerRecord = customerHistory[0]?.clientes;
  const customerSpent = customerHistory.reduce((n,o)=>n+Number(o.total),0);
  const products = new Map<string,{name:string;quantity:number;value:number}>(); const categories = new Map<string,number>();
  for(const o of sales) for(const it of o.pedido_itens || []) { const k=it.produto_nome; const p=products.get(k)||{name:k,quantity:0,value:0}; p.quantity+=Number(it.quantidade); p.value+=Number(it.subtotal); products.set(k,p); categories.set(it.categoria_nome||'Sem categoria',(categories.get(it.categoria_nome||'Sem categoria')||0)+Number(it.subtotal)); }
  const ranked=[...products.values()].sort((a,b)=>b.quantity-a.quantity).slice(0,8);
  const span=Math.max(1,(new Date(`${range.to}T00:00:00`).getTime()-new Date(`${range.from}T00:00:00`).getTime())/86400000+1);
  const buckets=new Map<string,{sales:number;orders:number}>();
  for(const o of filtered){const date=new Date(o.created_at); const key=span>60?`Sem ${Math.ceil(date.getDate()/7)} · ${date.toLocaleDateString('pt-BR',{month:'short'})}`:date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}); const b=buckets.get(key)||{sales:0,orders:0}; b.sales+=Number(o.total); b.orders++; buckets.set(key,b);}
  const trend=[...buckets.entries()].reverse();
  const issued=new Date();
  const exportXlsx=()=>{
    const head=['Data','Hora','Cliente','Telefone','Valor'];
    const orderRows=filtered.map(o=>{const d=new Date(o.created_at);return[d.toLocaleDateString('pt-BR'),d.toLocaleTimeString('pt-BR'),o.clientes?.nome,formatBrazilPhone(o.clientes?.telefone||''),Number(o.total)];});
    const itemRows=filtered.flatMap(o=>(o.pedido_itens||[]).map(i=>[o.id.slice(0,8),new Date(o.created_at).toLocaleDateString('pt-BR'),o.clientes?.nome,i.produto_nome,i.tamanho?.label||'',(i.complementos||[]).map((c:any)=>c.name).join(', '),i.quantidade,Number(i.preco_unitario),Number(i.subtotal)]));
    const clientsRows=[...clients.values()].map(c=>[c.name,formatBrazilPhone(c.phone),c.orders,c.spent,new Date(c.first).toLocaleDateString('pt-BR'),new Date(c.last).toLocaleDateString('pt-BR')]);
    const periodLabel = `${new Date(`${range.from}T00:00:00`).toLocaleDateString('pt-BR')} até ${new Date(`${range.to}T00:00:00`).toLocaleDateString('pt-BR')}`;
    downloadXlsx([
      {name:'Resumo',rows:[[],[],[],[],[],[],['Açaiteria Alves','Relatório de Vendas'],['Período',periodLabel],['Emitido em',issued.toLocaleString('pt-BR')],['Entrada total',total],['Quantidade de pedidos',filtered.length],['Média de vendas',sales.length?total/sales.length:0],['Clientes',clients.size]]},
      {name:'Pedidos',rows:[head,...orderRows]},
      {name:'Itens dos pedidos',rows:[['Pedido','Data','Cliente','Produto','Tamanho','Complementos','Quantidade','Preço unitário','Subtotal'],...itemRows]},
      {name:'Clientes',rows:[['Nome','Telefone','Quantidade de pedidos','Total gasto','Primeiro pedido','Último pedido'],...clientsRows]}
    ],`relatorio-vendas-acaiteria-alves-${dateKey(issued)}.xlsx`);
  };
  const printReport=()=>{
    const w=window.open('','_blank'); if(!w)return; w.opener=null;
    const rows=filtered.map(o=>`<tr><td>${when(o.created_at)}</td><td>${escapeHtml(o.clientes?.nome||'Cliente')}</td><td>${escapeHtml(formatBrazilPhone(o.clientes?.telefone||''))}</td><td>${money(Number(o.total))}</td></tr>`).join('');
    const top=ranked.map(p=>`<li>${escapeHtml(p.name)}: ${p.quantity} un. (${money(p.value)})</li>`).join('');
    const daily=trend.map(([day,b])=>`<tr><td>${day}</td><td>${money(b.sales)}</td><td>${b.orders}</td></tr>`).join('');
    const periodLabel=`${new Date(`${range.from}T00:00:00`).toLocaleDateString('pt-BR')} até ${new Date(`${range.to}T00:00:00`).toLocaleDateString('pt-BR')}`;
    w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>relatorio-vendas-acaiteria-alves-${dateKey(issued)}.pdf</title><style>body{font:14px Arial;color:#25132d;padding:30px}header{display:flex;align-items:center;gap:18px;border-bottom:2px solid #4b1764;padding-bottom:18px}header img{width:90px;height:90px;object-fit:contain}h1{margin:0;color:#421357}h2{margin-top:28px;color:#421357}section{display:flex;gap:30px;flex-wrap:wrap}.card{background:#f5f1f7;padding:14px;border-radius:10px;min-width:150px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid #ddd}@media print{body{padding:0}}</style></head><body><header><img src="${location.origin}/logo.webp"><div><h1>Açaiteria Alves</h1><h2>Relatório de Vendas</h2><p>Período: ${periodLabel}</p><small>Emitido em: ${issued.toLocaleString('pt-BR')}</small></div></header><section><div class="card">Entrada total<br><b>${money(total)}</b></div><div class="card">Pedidos<br><b>${filtered.length}</b></div><div class="card">Média de vendas<br><b>${money(sales.length?total/sales.length:0)}</b></div><div class="card">Clientes<br><b>${clients.size}</b></div></section><h2>Resumo de vendas por período</h2><table><thead><tr><th>Período</th><th>Faturamento</th><th>Pedidos</th></tr></thead><tbody>${daily}</tbody></table><h2>Produtos mais vendidos</h2><ol>${top}</ol><h2>Pedidos do período</h2><table><thead><tr><th>Data e hora</th><th>Cliente</th><th>Telefone</th><th>Valor</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();
  };
  const statCards=[['Entrada total',money(total),CircleDollarSign],['Pedidos',String(filtered.length),ShoppingBag],['Média de vendas',money(sales.length?total/sales.length:0),TrendingUp],['Clientes',String(clients.size),Users],['Produto mais vendido',ranked[0]?.name||'—',ShoppingBag]] as const;

  return <div className="min-h-screen bg-[#f7f5f9] text-slate-800">
    <header className="sticky top-0 z-30 border-b border-purple-100 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><img src="/logo.webp" className="h-11 w-11 object-contain"/><div><p className="text-xs font-semibold uppercase tracking-wider text-purple-500">Painel administrativo</p><h1 className="font-black text-[#35074a]">Dashboard de vendas</h1></div></div><button onClick={onBack} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><ArrowLeft size={16}/>Painel</button></div></header>
    <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 sm:py-8">
      <section className="flex flex-col gap-3 rounded-2xl border border-purple-100 bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-bold text-slate-600">Período<select value={period} onChange={e=>setPeriod(e.target.value as Period)} className="mt-1 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="month">Este mês</option><option value="prevmonth">Mês anterior</option><option value="custom">Personalizado</option></select></label>{period==='custom'&&<><label className="text-xs font-bold text-slate-600">De<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label><label className="text-xs font-bold text-slate-600">Até<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label></>}</div><div className="flex flex-wrap gap-2"><button onClick={()=>void refresh()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><RefreshCw size={16}/>Atualizar</button><button onClick={printReport} disabled={!orders.length} className="inline-flex items-center gap-2 rounded-xl bg-[#4b1764] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><Printer size={16}/>Imprimir PDF</button><button onClick={exportXlsx} disabled={!orders.length} className="inline-flex items-center gap-2 rounded-xl bg-[#5d9e23] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><FileSpreadsheet size={16}/>Exportar Excel</button></div></section>
      {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
      {loading?<div className="rounded-2xl bg-white p-12 text-center text-sm font-semibold text-slate-500"><span className="mx-auto mb-3 block h-8 w-8 animate-spin rounded-full border-4 border-purple-100 border-t-purple-700"/>Carregando dados reais do Supabase…</div>:<>
      <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-5">{statCards.map(([label,value,Icon])=><article key={label} className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><span className="rounded-xl bg-purple-50 p-2 text-purple-700"><Icon size={19}/></span></div><p className={`mt-3 truncate text-2xl font-black ${label === 'Entrada total' ? 'text-[#5d9e23]' : 'text-[#35074a]'}`} title={value}>{value}</p></article>)}</section>
      <section className="grid gap-4 lg:grid-cols-2"><Chart title="Vendas ao longo do tempo" labels={trend.map(([k])=>k)} values={trend.map(([,b])=>b.sales)} display={v=>money(v)} /><Chart title="Pedidos ao longo do tempo" labels={trend.map(([k])=>k)} values={trend.map(([,b])=>b.orders)} display={v=>String(v)} /><RankBars title="Produtos mais vendidos" rows={ranked.map(p=>[p.name,p.quantity,`${p.quantity} un. · ${money(p.value)}`])}/><RankBars title="Faturamento por categoria" rows={[...categories.entries()].sort((a,b)=>b[1]-a[1]).map(([n,v])=>[n,v,money(v)])}/></section>
      <section className="overflow-hidden rounded-2xl border border-purple-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-4 sm:px-5"><h2 className="font-black text-[#35074a]">Pedidos do período</h2><p className="mt-1 text-xs text-slate-500">Pedidos salvos entram automaticamente nas vendas.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-purple-50/60 text-xs uppercase text-slate-500"><tr>{['Data','Cliente','Telefone','Valor','Produtos',''].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>setSelected(o)} className="cursor-pointer border-t border-slate-100 hover:bg-purple-50/40"><td className="whitespace-nowrap px-4 py-3">{when(o.created_at)}</td><td className="px-4 py-3 font-bold">{o.clientes?.nome||'Cliente'}</td><td className="px-4 py-3">{formatBrazilPhone(o.clientes?.telefone||'')}</td><td className="whitespace-nowrap px-4 py-3 font-bold">{money(Number(o.total))}</td><td className="max-w-64 truncate px-4 py-3">{o.pedido_itens?.map(i=>`${i.quantidade}× ${i.produto_nome}`).join(', ')}</td><td className="px-4 py-3 text-purple-700">Detalhes</td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">Nenhum pedido encontrado neste período.</td></tr>}</tbody></table></div></section>
      <section className="overflow-hidden rounded-2xl border border-purple-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-4"><h2 className="font-black text-[#35074a]">Clientes no período</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-purple-50/60 text-xs uppercase text-slate-500"><tr>{['Nome','Telefone','Pedidos','Total gasto','Primeiro pedido','Último pedido'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{[...clients.values()].map(c=><tr key={c.phone} onClick={()=>setSelectedClientId(c.id)} className="cursor-pointer border-t border-slate-100 hover:bg-purple-50/40"><td className="px-4 py-3 font-bold">{c.name}</td><td className="px-4 py-3">{formatBrazilPhone(c.phone)}</td><td className="px-4 py-3">{c.orders}</td><td className="px-4 py-3">{money(c.spent)}</td><td className="px-4 py-3">{new Date(c.first).toLocaleDateString('pt-BR')}</td><td className="px-4 py-3">{new Date(c.last).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>
      </>}
    </main>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-3" onClick={()=>setSelected(null)}><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-start justify-between"><div><p className="text-xs font-bold uppercase text-purple-600">Detalhes do pedido · {when(selected.created_at)}</p><h2 className="mt-1 text-xl font-black text-[#35074a]">{selected.clientes?.nome}</h2><p className="text-sm text-slate-600">{formatBrazilPhone(selected.clientes?.telefone||'')}</p></div><button onClick={()=>setSelected(null)} aria-label="Fechar"><X/></button></div><div className="grid gap-3 rounded-xl bg-purple-50 p-4 text-sm sm:grid-cols-2"><p><b>Entrega:</b> {selected.tipo_entrega}</p><p><b>Pagamento:</b> {selected.forma_pagamento}</p><p className="sm:col-span-2"><b>Endereço:</b> {[selected.endereco,selected.bairro,selected.ponto_referencia].filter(Boolean).join(' · ')||'Retirada no local'}</p><p><b>Subtotal:</b> {money(Number(selected.subtotal))}</p><p><b>Taxa:</b> {money(Number(selected.taxa_entrega))}</p><p><b>Total:</b> {money(Number(selected.total))}</p>{selected.observacoes&&<p className="sm:col-span-2"><b>Observações:</b> {selected.observacoes}</p>}</div><h3 className="mb-2 mt-5 font-black">Itens</h3><div className="space-y-3">{selected.pedido_itens?.map(item=><article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><b>{item.produto_nome}</b><b>{money(Number(item.subtotal))}</b></div><ul className="mt-2 list-inside list-disc text-sm text-slate-600"><li>Quantidade: {item.quantidade}</li>{item.tamanho?.label&&<li>Tamanho: {item.tamanho.label}</li>}{item.detalhes?.tipo&&<li>Opção: {String(item.detalhes.tipo)}</li>}{item.detalhes?.is_combo&&item.detalhes?.units&&<li>Combo: {String(item.detalhes.units)} unidades</li>}{(item.complementos||[]).map((c:any)=><li key={c.id||c.name}>{c.name}</li>)}{item.cobertura&&<li>Cobertura: {item.cobertura}</li>}{item.observacoes&&<li>Observação: {item.observacoes}</li>}</ul><p className="mt-2 text-xs text-slate-500">Unitário: {money(Number(item.preco_unitario))} · Categoria: {item.categoria_nome}</p></article>)}</div></section></div>}
    {selectedClientId&&customerRecord&&<div className="fixed inset-0 z-[55] flex items-center justify-center bg-black/50 p-3" onClick={()=>setSelectedClientId(null)}><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-start justify-between"><div><p className="text-xs font-bold uppercase text-purple-600">Histórico do cliente</p><h2 className="mt-1 text-xl font-black text-[#35074a]">{customerRecord.nome}</h2><p className="text-sm text-slate-600">{formatBrazilPhone(customerRecord.telefone)}</p></div><button onClick={()=>setSelectedClientId(null)} aria-label="Fechar"><X/></button></div><div className="mb-4 grid grid-cols-2 gap-3 rounded-xl bg-purple-50 p-4 text-sm"><p><b>Pedidos:</b> {customerHistory.length}</p><p><b>Total gasto:</b> {money(customerSpent)}</p><p><b>Primeiro pedido:</b> {customerHistory.length?new Date(customerHistory[customerHistory.length-1].created_at).toLocaleDateString('pt-BR'):'—'}</p><p><b>Último pedido:</b> {customerHistory.length?new Date(customerHistory[0].created_at).toLocaleDateString('pt-BR'):'—'}</p></div><div className="space-y-2">{customerHistory.map(o=><button key={o.id} onClick={()=>{setSelected(o);setSelectedClientId(null);}} className="flex w-full items-center justify-between gap-3 rounded-xl border border-slate-200 p-3 text-left text-sm hover:bg-purple-50"><span>{when(o.created_at)}</span><b>{money(Number(o.total))}</b></button>)}</div></section></div>}
  </div>;
}

function Chart({title,labels,values,display}:{title:string;labels:string[];values:number[];display:(v:number)=>string}) {
  const max=Math.max(1,...values); return <article className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><h2 className="mb-4 font-black text-[#35074a]">{title}</h2>{values.length?<div className="grid grid-cols-3 gap-x-3 gap-y-5 sm:grid-cols-6">{values.map((v,i)=><div key={i} title={`${labels[i]} · ${display(v)}`} className="flex h-44 min-w-0 flex-col items-center justify-end gap-2 border-b border-slate-200 pb-2"><span className="w-full break-words text-center text-xs font-bold text-slate-700">{display(v)}</span><div className="w-full rounded-t-md bg-gradient-to-t from-purple-700 to-lime-400" style={{height:`${Math.max(3,v/max*72)}%`}}/><span className="w-full break-words text-center text-xs font-bold text-slate-700">{labels[i]}</span></div>)}</div>:<p className="py-12 text-center text-sm text-slate-400">Sem dados no período</p>}</article>
}
function RankBars({title,rows}:{title:string;rows:Array<[string,number,string]>}) {const max=Math.max(1,...rows.map(r=>r[1]));return <article className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><h2 className="mb-4 font-black text-[#35074a]">{title}</h2>{rows.length?<ol className="space-y-3">{rows.map(([name,value,label],i)=><li key={name}><div className="mb-1 flex justify-between gap-2 text-xs"><span className="truncate"><b className="mr-2 text-purple-700">{i+1}.</b>{name}</span><b className="shrink-0">{label}</b></div><div className="h-2 overflow-hidden rounded-full bg-purple-50"><div className="h-full rounded-full bg-gradient-to-r from-purple-700 to-lime-400" style={{width:`${Math.max(3,value/max*100)}%`}}/></div></li>)}</ol>:<p className="py-8 text-center text-sm text-slate-400">Sem vendas no período</p>}</article>}
